CREATE TABLE IF NOT EXISTS members (
    id BIGINT NOT NULL,
    guild_id BIGINT NOT NULL,
    infractions BIGINT NOT NULL DEFAULT 0,
    deaf BOOLEAN NOT NULL DEFAULT FALSE,
    mute BOOLEAN NOT NULL DEFAULT FALSE,
    banned BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id)
);