CREATE TABLE IF NOT EXISTS users (
    id BIGINT NOT NULL,
    offences INTEGER NOT NULL DEFAULT 0,
    deaf BOOLEAN NOT NULL DEFAULT FALSE,
    mute BOOLEAN NOT NULL DEFAULT FALSE,
    banned BOOLEAN NOT NULL DEFAULT FALSE,
    -- guild_id BIGINT NOT NULL,
    -- FOREIGN KEY (guild_id) REFERENCES guilds (id),
    PRIMARY KEY (id)
)