CREATE TABLE IF NOT EXISTS users (
    id BIGINT NOT NULL,
    locale VARCHAR,
    offences INTEGER NOT NULL DEFAULT 0,
    deafened BOOLEAN NOT NULL DEFAULT FALSE,
    silenced BOOLEAN NOT NULL DEFAULT FALSE,
    banned BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id)
)