# Copyright (C) 2024 Kawaxte
# 
# wakalaka-rs is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# wakalaka-rs is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public License
# along with wakalaka-rs. If not, see <http://www.gnu.org/licenses/>.

name: Bug Report
description: |
  Report a bug to help improve yours truly.
title: "[Bug Report]:"
labels: [ bug ]
assignees:
  - Kawaxte
body:
  - type: markdown
    attributes:
      value: |
        Before submitting a bug report, ensure that you have searched for similar reports. There is a chance that somebody else has already reported the same issue.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: |
        What is the bug you are reporting?
      placeholder: |
        When I did X, ...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: |
        What are we supposed to do to reproduce the bug(s)?
      placeholder: |
        1. Do X...
        2. Wait for Y ...
        3. Click on Z ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: |
        What did you expect to happen?
      placeholder: |
        I expected that ...
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: |
        What actually happened?
      placeholder: |
        Well, when X ...
    validations:
      required: true
  - type: textarea
    id: media
    attributes:
      label: Media
      description: |
        Attach an image, gif, or video that demonstrates the bug(s), if applicable.
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        On what system did you encounter the bug(s) on?
      placeholder: |
        The bug occurred on ...
    validations:
      required: true